-- CreateEnum
CREATE TYPE "Plan" AS ENUM ('FREE', 'PRO', 'PREMIUM');

-- AlterTable
ALTER TABLE "Organization" ADD COLUMN     "nbrEvents" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "nbrUsers" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "plan" "Plan" NOT NULL DEFAULT 'FREE';
